### ISSUE TITLE
Generate PDFs Using API Token vs Auth Credentials

### ISSUE THREAD

**Issue by zburk** [matthewdowney/TogglPy#45]
I was trying `getDetailedReportPDF` and `getSummaryReportPDF` using `setAuthCredentials` but kept getting a `401 Bad Request` error. When I switched to using `setAPIKey` it worked fine. Is this a known issue that API tokens must be used for certain endpoints? Happy to update the docs if this is the case.

**Comment by matthewdowney** [comment]
Hmm I wasn't aware of this, but in the [documentation for the reports section of the API](https://github.com/toggl/toggl_api_docs/blob/master/reports.md#authentication) they write:

>You can authenticate in the reports API only with your API token. For HTTP Basic Auth you have to add the Authorization header with the request. The API token is the user name and the string 'api_token' is the password. Whenever possible please use the tools and interfaces provided by your http library to do Basic Auth (for example, curl uses the -u switch for that).

Pull request clarifying this would be welcome!

**Comment by zburk** [comment]
Thanks for the follow-up! I'll write it up
