### ISSUE TITLE
Update API Url Domain to api.track.toggl.com

### ISSUE THREAD

**Issue by gilberthdez** [matthewdowney/TogglPy#47]
toggl.com or www.toggl.com will no longer be a supported entry point for the Toggl Track API check:
- https://github.com/toggl/toggl_api_docs
- https://toggl.com/blog/api-documentation-change

**Comment by kunom** [comment]
Deadline is End of June 2021 (see API docs link above).

**Comment by markasbach** [comment]
It seems that the Toggl Reports API is also affected. Those URLs had been missed by pull request #48. Also I think that the version number of the package should be updated to reflect the change. So I've added pull request #49 to address these two issues.

**Comment by matthewdowney** [comment]
I think @pauloxnet should be able to do the deployment to PyPi, [since he's the maintainer there](https://pypi.org/project/TogglPy/), if he would be so kind, but if there's a way for me to do it as well that I'm not aware of I'm happy to!

**Comment by galloramiro** [comment]
Hi @pauloxnet srry for bother but the days are runing, coud I do something to help you lunch this in pypi?

**Comment by pauloxnet** [comment]
Hi all, sorry for the late reply. I'm no longer using togglpy, so if @matthewdowney or other contributors write here their pypi.org account names, I would assign you as mantainer.

**Comment by rafleze** [comment]
Hi all.
You can find the last version uploaded on pypi.org: https://pypi.org/project/TogglPy/
