### ISSUE TITLE
400 Bad request

### ISSUE THREAD

**Issue by ahbeheshti** [matthewdowney/TogglPy#53]
I get 400 bad request for functions ```stopTimeEntry``` and ```currentRunningTimeEntry```.
The issue can be resolved just by updating the method for those two functions.
```stopTimeEntry``` needs to use ```PUT``` and  ```currentRunningTimeEntry``` needs to use ```GET```.

I've installed this library by pip install and my current version is 0.1.2

**Comment by matthewdowney** [comment]
See #52
